-- Admin login accounts for Steve Weeks Music /admin
-- Run this against musician_db before using the admin login pages.

CREATE TABLE IF NOT EXISTS ADMIN_USER (
  ADMIN_USER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(64) NOT NULL,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_LOGIN DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (ADMIN_USER_ID),
  UNIQUE KEY UK_ADMIN_USER_USERNAME (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Long-lived "Stay logged in" tokens for /admin (also auto-created by adminRememberMe.php).
CREATE TABLE IF NOT EXISTS ADMIN_REMEMBER_TOKEN (
  TOKEN_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADMIN_USER_ID INT UNSIGNED NOT NULL,
  SELECTOR CHAR(32) NOT NULL,
  VALIDATOR_HASH CHAR(64) NOT NULL,
  EXPIRES_AT DATETIME NOT NULL,
  PRIMARY KEY (TOKEN_ID),
  UNIQUE KEY UK_REMEMBER_SELECTOR (SELECTOR),
  KEY IX_REMEMBER_USER (ADMIN_USER_ID),
  KEY IX_REMEMBER_EXPIRES (EXPIRES_AT),
  CONSTRAINT FK_REMEMBER_ADMIN_USER
    FOREIGN KEY (ADMIN_USER_ID) REFERENCES ADMIN_USER (ADMIN_USER_ID)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
