-- Admin login accounts for Steve Weeks Music /admin
-- Run this against musician_db before using the admin login pages.

CREATE TABLE IF NOT EXISTS ADMIN_USER (
  ADMIN_USER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(64) NOT NULL,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_LOGIN DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (ADMIN_USER_ID),
  UNIQUE KEY UK_ADMIN_USER_USERNAME (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
